/*
 * DendrogramDialog.java
 *
 * Created on 10. mai 2002, 18:50
 */
package no.uib.jexpress_modularized.somclust.visualization;

import java.io.Serializable;

/**
 *
 * @author bjarte dysvik
 */
public class DendrogramDialog extends javax.swing.JInternalFrame implements Serializable {

    /**
     * Creates new form DendrogramDialog
     */
    public DendrogramDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    buttonGroup1 = new javax.swing.ButtonGroup();
    buttonGroup2 = new javax.swing.ButtonGroup();
    buttonGroup3 = new javax.swing.ButtonGroup();
    jEPanel1 = new no.uib.jexpress_modularized.core.visualization.JEPanel();
    jPanel3 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    rb1SV = new javax.swing.JRadioButton();
    rb4SV = new javax.swing.JRadioButton();
    rb2SV = new javax.swing.JRadioButton();
    rb3SV = new javax.swing.JRadioButton();
    jPanel22 = new javax.swing.JPanel();
    columnsSV = new javax.swing.JCheckBox();
    jPanel21 = new javax.swing.JPanel();
    distanceSV = new javax.swing.JComboBox();
    jPanel4 = new javax.swing.JPanel();
    RowsSV = new javax.swing.JRadioButton();
    columns2SV = new javax.swing.JRadioButton();
    jLabel2 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jb3 = new javax.swing.JButton();
    jb4 = new javax.swing.JButton();

    setTitle("Hierarchical Clustering");
    setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/expresscomponents/Visuals/im/fclust.gif"))); // NOI18N

    jEPanel1.setPaintText(false);
    jEPanel1.setLayout(new java.awt.BorderLayout());

    jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(120, 120, 120)));
    jPanel3.setOpaque(false);
    jPanel3.setLayout(new java.awt.GridBagLayout());

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Linkage"));
    jPanel2.setOpaque(false);
    jPanel2.setLayout(new java.awt.GridLayout(4, 0));

    buttonGroup1.add(rb1SV);
    rb1SV.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    rb1SV.setText("Single Linkage");
    rb1SV.setOpaque(false);
    jPanel2.add(rb1SV);

    buttonGroup1.add(rb4SV);
    rb4SV.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    rb4SV.setText("Average Linkage (UPGMA)");
    rb4SV.setOpaque(false);
    jPanel2.add(rb4SV);

    buttonGroup1.add(rb2SV);
    rb2SV.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    rb2SV.setText("Average Linkage (WPGMA)");
    rb2SV.setOpaque(false);
    jPanel2.add(rb2SV);

    buttonGroup1.add(rb3SV);
    rb3SV.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    rb3SV.setText("Complete Linkage");
    rb3SV.setOpaque(false);
    jPanel2.add(rb3SV);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridheight = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    jPanel3.add(jPanel2, gridBagConstraints);

    jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder("Tree Properties"));
    jPanel22.setOpaque(false);
    jPanel22.setLayout(new java.awt.GridLayout(2, 0));

    columnsSV.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    columnsSV.setText("Cluster Columns");
    columnsSV.setOpaque(false);
    jPanel22.add(columnsSV);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    jPanel3.add(jPanel22, gridBagConstraints);

    jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder("Distance Measure"));
    jPanel21.setOpaque(false);

    distanceSV.setMaximumSize(new java.awt.Dimension(32767, 20));
    jPanel21.add(distanceSV);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    jPanel3.add(jPanel21, gridBagConstraints);

    jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(160, 160, 160)));
    jPanel4.setOpaque(false);
    jPanel4.setLayout(new java.awt.GridBagLayout());

    buttonGroup2.add(RowsSV);
    RowsSV.setSelected(true);
    RowsSV.setText("Rows");
    RowsSV.setOpaque(false);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    jPanel4.add(RowsSV, gridBagConstraints);

    buttonGroup2.add(columns2SV);
    columns2SV.setText("Columns");
    columns2SV.setOpaque(false);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    jPanel4.add(columns2SV, gridBagConstraints);

    jLabel2.setText("Cluster Way");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(2, 7, 2, 2);
    jPanel4.add(jLabel2, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    jPanel3.add(jPanel4, gridBagConstraints);

    jEPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

    jPanel1.setOpaque(false);
    jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

    jb3.setText("Ok");
    jb3.setOpaque(false);
    jPanel1.add(jb3);

    jb4.setText("Cancel");
    jb4.setOpaque(false);
    jb4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jb4ActionPerformed(evt);
      }
    });
    jPanel1.add(jb4);

    jEPanel1.add(jPanel1, java.awt.BorderLayout.SOUTH);

    getContentPane().add(jEPanel1, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb4ActionPerformed
    }//GEN-LAST:event_jb4ActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JRadioButton RowsSV;
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.ButtonGroup buttonGroup2;
  private javax.swing.ButtonGroup buttonGroup3;
  public javax.swing.JRadioButton columns2SV;
  public javax.swing.JCheckBox columnsSV;
  public javax.swing.JComboBox distanceSV;
  private no.uib.jexpress_modularized.core.visualization.JEPanel jEPanel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel21;
  private javax.swing.JPanel jPanel22;
  private javax.swing.JPanel jPanel3;
  public javax.swing.JPanel jPanel4;
  public javax.swing.JButton jb3;
  public javax.swing.JButton jb4;
  public javax.swing.JRadioButton rb1SV;
  public javax.swing.JRadioButton rb2SV;
  public javax.swing.JRadioButton rb3SV;
  public javax.swing.JRadioButton rb4SV;
  // End of variables declaration//GEN-END:variables
}
